export const table = {

	teetharound:[
		{
			name:'牙石',
			id:"0",
			groups:[
				{
					type:'s',
					id:"00",
					group:[
						{
							name:'Ⅰ',
							id:"000",
							title:'牙石',
							check:'0'
						},
						{
							name:'Ⅱ',
							id:"001",
							title:'牙石',
							check:'0'
						},
						{
							name:'Ⅲ',
							id:"002",
							title:'牙石',
							check:'0'
						}
					]
				}
			]
		},
		{
			name:'松动',
			id:"1",
			groups:[
				{
					type:'s',
					id:'10',
					group:[
						{
							name:'Ⅰ',
							id:"010",
							title:'松动',
							check:'0'
						},
						{
							name:'Ⅱ',
							id:"011",
							title:'松动',
							check:'0'
						},
						{
							name:'Ⅲ',
							id:"012",
							title:'松动',
							check:'0'
						}
					]
				}
			]
		},
		{
			name:'出血',
			id:"2",
			groups:[
				{
					type:'s',
					id:'20',
					group:[
						{
							name:'Ⅰ',
							id:"020",
							title:'出血',
							check:'0'
						},
						{
							name:'Ⅱ',
							id:"021",
							title:'出血',
							check:'0'
						},
						{
							name:'Ⅲ',
							id:"022",
							title:'出血',
							check:'0'
						},
						{
							name:'Ⅳ',
							id:"023",
							title:'出血',
							check:'0'
						},
						{
							name:'Ⅴ',
							id:"024",
							title:'出血',
							check:'0'
						}
					]
				}
			]
		}
	],
	mucosa:[
		{
			name:'粘膜',
			id:'0',
			groups:[
				{
					type:'m',
					id:'00',
					group:[
						{
							name:'正常',
							id:"000",
							title:'粘膜',
							check:'0'
						},
						{
							name:'白色斑块',
							id:"001",
							title:'粘膜',
							check:'0'
						},
						{
							name:'红色斑块',
							id:"002",
							title:'粘膜',
							check:'0'
						},
						{
							name:'扁平苔藓',
							id:"003",
							title:'粘膜',
							check:'0'
						},
						{
							name:'溃疡',
							id:"004",
							title:'粘膜',
							check:'0'
						},
						{
							name:'其他',
							id:"005",
							title:'粘膜',
							check:'0',
							describe:''
						},
					]
				}
			]
		}	 		
	],
	surgery:[	
		{
			name:'开口度',
			id:"1",
			groups:[
				{
					type:'s',
					id:"10",
					group:[
						{
							name:'三指宽度',
							id:"100",
							title:'开口度',
							check:'0'
						},
						{
							name:'两指宽度',
							id:"101",
							title:'开口度',
							check:'0'
						},
						{
							name:'一指宽度，甚至更小',
							id:"102",
							title:'开口度',
							check:'0'
						}
					]
				}
			]
		},
		{
			name:'开口型',
			id:"2",
			groups:[
				{
					type:'s',
					id:'20',
					group:[
						{
							name:'直线',
							id:"200",
							title:'开口型',
							check:'0'
						},
						{
							name:'偏左',
							id:"201",
							title:'开口型',
							check:'0'
						},
						{
							name:'偏右',
							id:"202",
							title:'开口型',
							check:'0'
						}
					]
				}
			]
		},
		{ /* lv1 */
			name:'面型',
			id:"3",
			groups:[
				{  /*    lv2 */
					type:'s',
					id:'30',
					group:[
						{  /*  lv3 */
							name:'大致对称',
							id:"300",
							title:'面型',
							check:'0'
						},
						{/*  lv3 */
							name:'中线偏左',
							id:"301",
							title:'面型',
							check:'0'
						},
						{/*  lv3 */
							name:'中线偏右',
							id:"302",
							title:'面型',
							check:'0'
						}
					]
				},
				{ /*    lv2 */
					type:'s',
					id:'31',
					group:[
						{
							name:'直面型',
							id:"310",
							title:'面型',
							check:'0'
						},
						{
							name:'凹面型',
							id:"311",
							title:'面型',
							check:'0'
						},
						{
							name:'凸面型',
							id:"312",
							title:'面型',
							check:'0'
						}
					]
				}
			]
		},
		{
			name:'牙列',
			id:'4',
			groups:[
				{
					type:'s',
					id:'40',
					group:[
						{
							name:'正常',
							id:'400',
							title:'牙列',
							check:'0'
						},
						{
							name:'拥挤',
							id:'401',
							title:'牙列',
							check:'0'
						},
						{
							name:'间隙',
							id:'402',
							title:'牙列',
							check:'0'
						}
					]
				}
			]
		},
		{
			name:'磨牙关系',
			id:'5',
			groups:[
				{
					type:'s',
					id:'50',
					group:[
						{
							name:'Ⅰ',
							id:'500',
							title:'磨牙关系',
							check:'0'
						},
						{
							name:'Ⅱ',
							id:'501',
							title:'磨牙关系',
							check:'0'
						},
						{
							name:'Ⅲ',
							id:'502',
							title:'磨牙关系',
							check:'0'
						}
					]
				}
			]
		},
	    {
           name:"前牙关系",
           id:'6',
           groups:[
             {
             	type:'s',
             	id:'60',
                group:[
                   {
                   	  name:'正常',
                   	  id:'600',
					  title:'前牙关系',
					  check:'0'
                   },
                   {
                      name:'反合',
                      id:"601",
					  title:'前牙关系',
					  check:'0'
                   },
                   {
                      name:'开合',
                      id:"602",
					  title:'前牙关系',
					  check:'0'
                   },
                   {
                   	  name:'对刃',
                   	  id:"603",
					  title:'前牙关系',
					  check:'0'
                   }

                ]
             },
             {
             	type:'m',
             	id:'61',
             	group:[
                   {
                      name: '深覆盖',
                      id:"610",
					  title:'前牙关系',
					  check:'0'
                   },
                   {
                      name: '深覆合',
                      id:'611',
					  title:'前牙关系',
					  check:'0'
                   }
     
             	]
             }
           ]
	    },
	    {
			name:'系带',
			id:'7',
			groups:[
				{
					type:'m',
					id:'70',
					group:[
						{
							name:'唇系带过低',
							id:"700",
					  		title:'系带',
							check:'0'
						},
						{
							name:'舌系带过短',
							id:'701',
					  		title:'系带',
							check:'0'
						},
						{
							name:'正常',
							id:'702',
					  		title:'系带',
							check:'0'
						}
					]
				}
			]
		},
		{
			name:'TMG',
			id:'8',
			groups:[
				{
					type:'m',
					id:'80',
					group:[
						{
							name:'关节弹响',
							id:'800',
					  		title:'TMG',
							check:'0'
						},
						{
							name:'关节压痛',
							id:'801',
					  		title:'TMG',
							check:'0'
						},
						{
							name:'关节脱位',
							id:'802',
					  		title:'TMG',
							check:'0'
						}
					]
				}
			]
		}
	]
}
